### ISSUE TITLE
Plans for SFSymbols2 categories

### ISSUE THREAD

**Issue by aaronpearce** [Nirma/SFSymbol#13]
Is there any plan to include the SFSymbol2 into categories somehow?

**Comment by Rspoon3** [comment]
I suggest you just fork the repository and take some time to do it yourself. Then you can submit a pull request.

**Comment by aaronpearce** [comment]
I was more asking if this was a feature that the owner of this repository wanted in the project than for them to do it.

**Comment by Rspoon3** [comment]
Ah I see. Well I think it would be a good addition.

**Comment by Nirma** [comment]
@aaronpearce Yeah, that could be useful. I am working on a bit of an update since things changed for SFSymbols in WWDC21. This might be the time to play with the idea of adding this in.
