### ISSUE TITLE
NSImage init(...) is unavailable in Mac Catalyst

### ISSUE THREAD

**Issue by honkmaster** [Nirma/SFSymbol#20]
The project can not be used with a Mac Catalyst application.
There is an error in NSImage+SFSymbol.swift.

`'init(systemSymbolName:accessibilityDescription:)' is unavailable in Mac Catalyst`

**Comment by thereaderfortyfive** [comment]
Does it work with Mac Catalyst yet?

**Comment by adamwulf** [comment]
I have a PR for catalyst support. The image extensions aren't available, so you'll need to make those yourself, but all the enums and symbols are available: https://github.com/Nirma/SFSymbol/pull/26

**Comment by Nirma** [comment]
Closing for now! Thanks everyone.
