### ISSUE TITLE
This is amazing 

### ISSUE THREAD

**Issue by thereaderfortyfive** [Nirma/SFSymbol#21]
Thank you very much. Can we expect an update in August again?

**Comment by Nirma** [comment]
@thereaderfortyfive Yes! I will push the preview branch soon! Thank you for checking in.

**Comment by tahirmt** [comment]
Curious if it was written manually or generated somehow?

**Comment by Nirma** [comment]
@thereaderfortyfive Updated so for now I am going to close this issue! Thanks for the support!

**Comment by Nirma** [comment]
@tahirmt Yes it is! I wrote a little script that parsed a list of SFSymbols and then a super tiny generator that creates these enums. 

Recently I moved to the nested enum style so I had to write another code generator.
